---
- name: Install Nginx and PHP on webserver
  hosts: webserver
  become: true

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Install PHP and its dependencies
      yum:
        name:
          - php 
          - php-mysqlnd
          - php-gd 
          - php-curl
        state: present

    
