---
- name: Install Nginx and PHP on webserver
  hosts: webserver
  become: true
  
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Install PHP and its dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-mysqlnd
        - php-gd
        - php-curl
